const aliases = (prefix = `src`) => ({
  '@templates': `${prefix}/templates`,
  '@components': `${prefix}/components`,
  '@accordions': `${prefix}/components/accordions`,
  '@avatars': `${prefix}/components/avatars`,
  '@buttons': `${prefix}/components/buttons`,
  '@cards': `${prefix}/components/cards`,
  '@dropdowns': `${prefix}/components/dropdowns`,
  '@filters': `${prefix}/components/filters`,
  '@forms': `${prefix}/components/forms`, 
  '@checkboxes': `${prefix}/components/forms/checkboxes`, 
  '@radioButtons': `${prefix}/components/forms/radioButtons`, 
  '@selects': `${prefix}/components/forms/selects`, 
  '@textFields': `${prefix}/components/forms/textFields`, 

  '@icons': `${prefix}/components/icons`,
  '@layout': `${prefix}/components/layout`,
  '@footers': `${prefix}/components/layout/footers`,
  '@headers': `${prefix}/components/layout/headers`,
  '@sideBars': `${prefix}/components/layout/sideBars`,
  '@tabs': `${prefix}/components/layout/tabs`,

  '@lists': `${prefix}/components/lists`,
  '@modals': `${prefix}/components/modals`,
  '@steppers': `${prefix}/components/steppers`,
  '@tables': `${prefix}/components/tables`,
  '@rowsTable': `${prefix}/components/tables/rowsTable`,
  '@paginations': `${prefix}/components/tables/paginations`,
  '@tags': `${prefix}/components/tags`,
  '@uploaders': `${prefix}/components/uploaders`,
  '@wrappers': `${prefix}/components/wrappers`,
  '@popups': `${prefix}/components/popups`,
  '@config': `${prefix}/config`,
  '@enums': `${prefix}/enums`,
  '@hooks': `${prefix}/hooks`,
  '@styles': `${prefix}/styles`,
  '@utils': `${prefix}/utils`,
  '@state': `${prefix}/state`,
  '@types': `${prefix}/types`,
  '@storybookHelpers': '../.storybook/helpers',

  '@assets': `${prefix}/assets`,
  '@pages': `${prefix}/pages`,
  '@api': `${prefix}/api`,
  '@context': `${prefix}/context`,
  '@reducers': `${prefix}/reducers`,
  '@constants': `${prefix}/constants`,
  '@services': `${prefix}/services`,
  '@containers': `${prefix}/containers`,
  '@layouts': `${prefix}/layouts`,
  '@helpers': `${prefix}/helpers`,
  '@routes': `${prefix}/routes`,
  '@theme': `${prefix}/theme`,
});

export default  aliases;
